spring:
  application:
    name: spring-oauth-demo
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/demo
server:
  port: 8081
logging:
  level:
    org.springframework.security: debug